//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TCPResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TCPResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.TCPResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Penworthy Company has been providing an exceptional selection of children&apos;s books to schools and public libraries in the United States since 1982.  We are the exclusive source for Penworthy Prebound Books – the most attractive and durable children’s books on the market.  Our expert sales representatives provide personalized customer service that libraries can trust.  In short, The Penworthy Company makes buying children’s books the pleasure it ought to be!®.
        /// </summary>
        internal static string AboutUsIntoductionText {
            get {
                return ResourceManager.GetString("AboutUsIntoductionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accelerated Reader.
        /// </summary>
        internal static string AcceleratedReaderText {
            get {
                return ResourceManager.GetString("AcceleratedReaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Quotes :.
        /// </summary>
        internal static string ActiveQuoteText {
            get {
                return ResourceManager.GetString("ActiveQuoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Books.
        /// </summary>
        internal static string ActivityBookText {
            get {
                return ResourceManager.GetString("ActivityBookText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        internal static string AddNewText {
            get {
                return ResourceManager.GetString("AddNewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string AllText {
            get {
                return ResourceManager.GetString("AllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AR Level.
        /// </summary>
        internal static string ARLevelText {
            get {
                return ResourceManager.GetString("ARLevelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AR Quiz #.
        /// </summary>
        internal static string ARQuizText {
            get {
                return ResourceManager.GetString("ARQuizText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arts/Recreation.
        /// </summary>
        internal static string ArtText {
            get {
                return ResourceManager.GetString("ArtText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Account for Merged Quote :.
        /// </summary>
        internal static string AssignAccountMergeText {
            get {
                return ResourceManager.GetString("AssignAccountMergeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string AuthorText {
            get {
                return ResourceManager.GetString("AuthorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACK.
        /// </summary>
        internal static string BackText {
            get {
                return ResourceManager.GetString("BackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To Products.
        /// </summary>
        internal static string BackToProduct {
            get {
                return ResourceManager.GetString("BackToProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string BarCodeText {
            get {
                return ResourceManager.GetString("BarCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding Type.
        /// </summary>
        internal static string BindingTypeText {
            get {
                return ResourceManager.GetString("BindingTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue star indicates titles related to past purchases..
        /// </summary>
        internal static string BlueStarText {
            get {
                return ResourceManager.GetString("BlueStarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Book.
        /// </summary>
        internal static string BoardBookText {
            get {
                return ResourceManager.GetString("BoardBookText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books for boys.
        /// </summary>
        internal static string BookForBoyText {
            get {
                return ResourceManager.GetString("BookForBoyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books for girls.
        /// </summary>
        internal static string BookForGitlText {
            get {
                return ResourceManager.GetString("BookForGitlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book format.
        /// </summary>
        internal static string BookFormatText {
            get {
                return ResourceManager.GetString("BookFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puppets Category.
        /// </summary>
        internal static string BookGroupText {
            get {
                return ResourceManager.GetString("BookGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $20.00.
        /// </summary>
        internal static string BooksPriceValue {
            get {
                return ResourceManager.GetString("BooksPriceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoodNight Moon.
        /// </summary>
        internal static string BookText {
            get {
                return ResourceManager.GetString("BookText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Up.
        /// </summary>
        internal static string BootomUpText {
            get {
                return ResourceManager.GetString("BootomUpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build With Categories.
        /// </summary>
        internal static string BuildWithCatalogsText {
            get {
                return ResourceManager.GetString("BuildWithCatalogsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build With KPL.
        /// </summary>
        internal static string BuildWithKPLText {
            get {
                return ResourceManager.GetString("BuildWithKPLText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice To.
        /// </summary>
        internal static string CalTagInvoiceToText {
            get {
                return ResourceManager.GetString("CalTagInvoiceToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string CalTagSendText {
            get {
                return ResourceManager.GetString("CalTagSendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cataloging Complete.
        /// </summary>
        internal static string CatalogCompleteText {
            get {
                return ResourceManager.GetString("CatalogCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Hold:.
        /// </summary>
        internal static string CatalogDisplayText {
            get {
                return ResourceManager.GetString("CatalogDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cataloging InComplete.
        /// </summary>
        internal static string CatalogInCompleteText {
            get {
                return ResourceManager.GetString("CatalogInCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cataloging.
        /// </summary>
        internal static string CatalogInfoText {
            get {
                return ResourceManager.GetString("CatalogInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cataloging Price per Book.
        /// </summary>
        internal static string CatalogingPriceperBookText {
            get {
                return ResourceManager.GetString("CatalogingPriceperBookText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string CatalogNoneText {
            get {
                return ResourceManager.GetString("CatalogNoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose position and alignment for non-spine labels.
        /// </summary>
        internal static string CatalogShelfReadyOptBarcodeText {
            get {
                return ResourceManager.GetString("CatalogShelfReadyOptBarcodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose application position and alignment for UP TO 3 spine labels (additional labels choose Unapplied).
        /// </summary>
        internal static string CatalogShelfReadyOptSpineLabelText {
            get {
                return ResourceManager.GetString("CatalogShelfReadyOptSpineLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View your cataloging requirements. Contact your Penworthy representative with required changes.
        /// </summary>
        internal static string CatCompleteText {
            get {
                return ResourceManager.GetString("CatCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter List.
        /// </summary>
        internal static string CategoriesText {
            get {
                return ResourceManager.GetString("CategoriesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string categoryText {
            get {
                return ResourceManager.GetString("categoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact your Penworthy representative with your cataloging requirements.
        /// </summary>
        internal static string CatIncompleteText {
            get {
                return ResourceManager.GetString("CatIncompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangepassowrdText {
            get {
                return ResourceManager.GetString("ChangepassowrdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter Books.
        /// </summary>
        internal static string ChapterBookText {
            get {
                return ResourceManager.GetString("ChapterBookText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Puppets.
        /// </summary>
        internal static string CharacterPuppetText {
            get {
                return ResourceManager.GetString("CharacterPuppetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        internal static string CharacterText {
            get {
                return ResourceManager.GetString("CharacterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character purchased before.
        /// </summary>
        internal static string CharPurchasedBeforeText {
            get {
                return ResourceManager.GetString("CharPurchasedBeforeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string ClassText {
            get {
                return ResourceManager.GetString("ClassText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        internal static string ClearAllText {
            get {
                return ResourceManager.GetString("ClearAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseText {
            get {
                return ResourceManager.GetString("CloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to close this window.
        /// </summary>
        internal static string Closethiswindow {
            get {
                return ResourceManager.GetString("Closethiswindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penworthy&apos;s goal is to save you time in the selection process by bringing you the titles kids want to read in bindings that last. We offer new titles every month, helping you stay on top of the characters and series the kids in your library are requesting. Our collection of Penworthy Prebound Books is complemented by specially selected library bound titles, board books and Folkmanis® Puppets..
        /// </summary>
        internal static string CollectionDescription {
            get {
                return ResourceManager.GetString("CollectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        internal static string columnfilterText {
            get {
                return ResourceManager.GetString("columnfilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string CommentText {
            get {
                return ResourceManager.GetString("CommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concepts.
        /// </summary>
        internal static string ConceptText {
            get {
                return ResourceManager.GetString("ConceptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string CopyrightText {
            get {
                return ResourceManager.GetString("CopyrightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COVER.
        /// </summary>
        internal static string CoverText {
            get {
                return ResourceManager.GetString("CoverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string CreateDateText {
            get {
                return ResourceManager.GetString("CreateDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Quote.
        /// </summary>
        internal static string CreateNewQuoteText {
            get {
                return ResourceManager.GetString("CreateNewQuoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Date:.
        /// </summary>
        internal static string CurrentDateText {
            get {
                return ResourceManager.GetString("CurrentDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Contact Name.
        /// </summary>
        internal static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string CustomerText {
            get {
                return ResourceManager.GetString("CustomerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to newuser.
        /// </summary>
        internal static string DafultPasswordText {
            get {
                return ResourceManager.GetString("DafultPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision Wizard.
        /// </summary>
        internal static string DecisionWizardliText {
            get {
                return ResourceManager.GetString("DecisionWizardliText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision Wizard :.
        /// </summary>
        internal static string DecisionWizardText {
            get {
                return ResourceManager.GetString("DecisionWizardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision Wizard.
        /// </summary>
        internal static string DecisionWizardText1 {
            get {
                return ResourceManager.GetString("DecisionWizardText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DecisionWizard.
        /// </summary>
        internal static string DecisionWizardViewText {
            get {
                return ResourceManager.GetString("DecisionWizardViewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemID,Price,Type,Title,Primarycharacter,Series.
        /// </summary>
        internal static string DefaultKPLValues {
            get {
                return ResourceManager.GetString("DefaultKPLValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultPenworthyDW.
        /// </summary>
        internal static string DefaultPenworthyDW {
            get {
                return ResourceManager.GetString("DefaultPenworthyDW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All.
        /// </summary>
        internal static string DeleteAllText {
            get {
                return ResourceManager.GetString("DeleteAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteText {
            get {
                return ResourceManager.GetString("DeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DescriptionText {
            get {
                return ResourceManager.GetString("DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string DetailList {
            get {
                return ResourceManager.GetString("DetailList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;You have looked at all of the titles in the selected category (indicated with a check in the box above: yes, no, maybe or new).  &lt;br/&gt;                                                                                                                                                                                                                                                                                 Here&apos;s what to do next: &lt;br/&gt;                                                                            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DWEndItemsText {
            get {
                return ResourceManager.GetString("DWEndItemsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string DWNameText {
            get {
                return ResourceManager.GetString("DWNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title,ItemId,Series,Author,AR,Lexile,DwstatusID,Price,Type.
        /// </summary>
        internal static string DWuserSelection {
            get {
                return ResourceManager.GetString("DWuserSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditText {
            get {
                return ResourceManager.GetString("EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EmailText {
            get {
                return ResourceManager.GetString("EmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’re sorry, but we do not recognize this email address. Please contact Penworthy at 800-262-2665 or.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Protectors.
        /// </summary>
        internal static string ExtraProtectorsText {
            get {
                return ResourceManager.GetString("ExtraProtectorsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiction/nonfiction.
        /// </summary>
        internal static string FicorNonFicText {
            get {
                return ResourceManager.GetString("FicorNonFicText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiction.
        /// </summary>
        internal static string FictionText {
            get {
                return ResourceManager.GetString("FictionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter List.
        /// </summary>
        internal static string FilterListText {
            get {
                return ResourceManager.GetString("FilterListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finger Puppets.
        /// </summary>
        internal static string FingerPuppetText {
            get {
                return ResourceManager.GetString("FingerPuppetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLY LEAF.
        /// </summary>
        internal static string FlyLeafText {
            get {
                return ResourceManager.GetString("FlyLeafText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string ForgotPasswordText {
            get {
                return ResourceManager.GetString("ForgotPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRONT.
        /// </summary>
        internal static string FrontText {
            get {
                return ResourceManager.GetString("FrontText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Further Refine.
        /// </summary>
        internal static string FurtherRefineText {
            get {
                return ResourceManager.GetString("FurtherRefineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold star indicates titles you have purchased..
        /// </summary>
        internal static string goldStarText {
            get {
                return ResourceManager.GetString("goldStarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grades 2-3.
        /// </summary>
        internal static string Grades23Text {
            get {
                return ResourceManager.GetString("Grades23Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grades 4+.
        /// </summary>
        internal static string Grades4Text {
            get {
                return ResourceManager.GetString("Grades4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grades K-1.
        /// </summary>
        internal static string GradesK1Text {
            get {
                return ResourceManager.GetString("GradesK1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics.
        /// </summary>
        internal static string GraphicsText {
            get {
                return ResourceManager.GetString("GraphicsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand Puppets.
        /// </summary>
        internal static string HandPuppetText {
            get {
                return ResourceManager.GetString("HandPuppetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string HistoryText {
            get {
                return ResourceManager.GetString("HistoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold-2 previews.
        /// </summary>
        internal static string Hold2previewsText {
            get {
                return ResourceManager.GetString("Hold2previewsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold-Audit.
        /// </summary>
        internal static string HoldAuditText {
            get {
                return ResourceManager.GetString("HoldAuditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold-Credit.
        /// </summary>
        internal static string HoldCreditText {
            get {
                return ResourceManager.GetString("HoldCreditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold-PO.
        /// </summary>
        internal static string HoldPOText {
            get {
                return ResourceManager.GetString("HoldPOText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold-Profile Incomplete.
        /// </summary>
        internal static string HoldProfileIncompleteText {
            get {
                return ResourceManager.GetString("HoldProfileIncompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold-Representative.
        /// </summary>
        internal static string HoldRepresentativeText {
            get {
                return ResourceManager.GetString("HoldRepresentativeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday.
        /// </summary>
        internal static string HolidayText {
            get {
                return ResourceManager.GetString("HolidayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision Wizard® – Presentation of the selections are displayed in secure portal on the website for the customer to review and make selections. 
        ///         Orders submitted to the ERP that began as a Decision Wizard® are considered Direct sales..
        /// </summary>
        internal static string HomeDWText {
            get {
                return ResourceManager.GetString("HomeDWText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/HomeSlide/Slide.
        /// </summary>
        internal static string HomeSlideImagePath {
            get {
                return ResourceManager.GetString("HomeSlideImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a mock up of a new page that provides a quick review of how to use the DW. We will have to improve the images, but this is the general idea..
        /// </summary>
        internal static string HowtouseDWText {
            get {
                return ResourceManager.GetString("HowtouseDWText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illustrator.
        /// </summary>
        internal static string IllustratorText {
            get {
                return ResourceManager.GetString("IllustratorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/.
        /// </summary>
        internal static string ImagesPath {
            get {
                return ResourceManager.GetString("ImagesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Cataloging.
        /// </summary>
        internal static string IncludeCatalogText {
            get {
                return ResourceManager.GetString("IncludeCatalogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InComplete.
        /// </summary>
        internal static string InComplete {
            get {
                return ResourceManager.GetString("InComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inside Back Options:.
        /// </summary>
        internal static string InsideBackOptionsText {
            get {
                return ResourceManager.GetString("InsideBackOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inside Front Options:.
        /// </summary>
        internal static string InsideFrontOptionsText {
            get {
                return ResourceManager.GetString("InsideFrontOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest Grade.
        /// </summary>
        internal static string InterestGradeText {
            get {
                return ResourceManager.GetString("InterestGradeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        internal static string ISBNText {
            get {
                return ResourceManager.GetString("ISBNText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item ID.
        /// </summary>
        internal static string ItemIDText {
            get {
                return ResourceManager.GetString("ItemIDText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/PenworthyImages/ScansCover-500/.
        /// </summary>
        internal static string ItemImagePath {
            get {
                return ResourceManager.GetString("ItemImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/PenworthyImages/Inside/.
        /// </summary>
        internal static string ItemInsideImagePath {
            get {
                return ResourceManager.GetString("ItemInsideImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item List Detailed View.
        /// </summary>
        internal static string ItemListDetailedView {
            get {
                return ResourceManager.GetString("ItemListDetailedView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item List.
        /// </summary>
        internal static string ItemListText {
            get {
                return ResourceManager.GetString("ItemListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item List View.
        /// </summary>
        internal static string ItemListView {
            get {
                return ResourceManager.GetString("ItemListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemListView.
        /// </summary>
        internal static string ItemListViewText {
            get {
                return ResourceManager.GetString("ItemListViewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Price.
        /// </summary>
        internal static string ItemPriceText {
            get {
                return ResourceManager.GetString("ItemPriceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        internal static string ItemText {
            get {
                return ResourceManager.GetString("ItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item List.
        /// </summary>
        internal static string KPLQuoteBuilderText {
            get {
                return ResourceManager.GetString("KPLQuoteBuilderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language/Literature.
        /// </summary>
        internal static string LanguageText {
            get {
                return ResourceManager.GetString("LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Updated.
        /// </summary>
        internal static string LastCustomerTouchText {
            get {
                return ResourceManager.GetString("LastCustomerTouchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2013/12/07.
        /// </summary>
        internal static string LastCutomerTouchDateValue {
            get {
                return ResourceManager.GetString("LastCutomerTouchDateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2013/12/10.
        /// </summary>
        internal static string LastPenworthyTouchDateValue {
            get {
                return ResourceManager.GetString("LastPenworthyTouchDateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        internal static string LastPenworthyTouchText {
            get {
                return ResourceManager.GetString("LastPenworthyTouchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn about Penworthy.
        /// </summary>
        internal static string LearnAbout {
            get {
                return ResourceManager.GetString("LearnAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leveled Readers.
        /// </summary>
        internal static string LeveledReadersText {
            get {
                return ResourceManager.GetString("LeveledReadersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lexile.
        /// </summary>
        internal static string LexileText {
            get {
                return ResourceManager.GetString("LexileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Penworthy&apos;s Librarian resources section, a special place where you can share ideas and stories with other librarians across the country. Click on one of the categories below to read stories within that category, or submit your own idea. If your idea appears on the web site, we&apos;ll send you a Penworthy Bear to say thank you!.
        /// </summary>
        internal static string LibrarianIntroduction {
            get {
                return ResourceManager.GetString("LibrarianIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dream Big!
        ///Summer Reading
        ///Activities.
        /// </summary>
        internal static string LibrarianItem1Text {
            get {
                return ResourceManager.GetString("LibrarianItem1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coloring Pages.
        /// </summary>
        internal static string LibrarianItem2Text {
            get {
                return ResourceManager.GetString("LibrarianItem2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Games.
        /// </summary>
        internal static string LibrarianItem3Text {
            get {
                return ResourceManager.GetString("LibrarianItem3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading
        ///Logs &amp; Certificates.
        /// </summary>
        internal static string LibrarianItem4Text {
            get {
                return ResourceManager.GetString("LibrarianItem4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Games &amp;
        ///Activites.
        /// </summary>
        internal static string LibrarianItem5Text {
            get {
                return ResourceManager.GetString("LibrarianItem5Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adopt-a-book
        ///Resources.
        /// </summary>
        internal static string LibrarianItem6Text {
            get {
                return ResourceManager.GetString("LibrarianItem6Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LibrarianResources.
        /// </summary>
        internal static string LibrarianResourcesText {
            get {
                return ResourceManager.GetString("LibrarianResourcesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library bound.
        /// </summary>
        internal static string LibraryBoundBookText {
            get {
                return ResourceManager.GetString("LibraryBoundBookText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print these fun activities to keep little hands busy in the library!.
        /// </summary>
        internal static string LibraryHeadIntro {
            get {
                return ResourceManager.GetString("LibraryHeadIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are viewing the List View.
        /// </summary>
        internal static string ListViewText {
            get {
                return ResourceManager.GetString("ListViewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABC Company.
        /// </summary>
        internal static string Loggedin {
            get {
                return ResourceManager.GetString("Loggedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged In For ABC Company.
        /// </summary>
        internal static string Loggedin1 {
            get {
                return ResourceManager.GetString("Loggedin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Create your account to access Penworthy&apos;s new and improved website!.
        /// </summary>
        internal static string ManagePasswordText {
            get {
                return ResourceManager.GetString("ManagePasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT US.
        /// </summary>
        internal static string MenuAboutUs {
            get {
                return ResourceManager.GetString("MenuAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string MenuAboutUsforbreadcrumbs {
            get {
                return ResourceManager.GetString("MenuAboutUsforbreadcrumbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT US.
        /// </summary>
        internal static string MenuContactus {
            get {
                return ResourceManager.GetString("MenuContactus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQs.
        /// </summary>
        internal static string MenuFaq {
            get {
                return ResourceManager.GetString("MenuFaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faqs.
        /// </summary>
        internal static string MenuFaq1 {
            get {
                return ResourceManager.GetString("MenuFaq1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fun &amp; Games.
        /// </summary>
        internal static string MenuFun {
            get {
                return ResourceManager.GetString("MenuFun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fun &amp; Games.
        /// </summary>
        internal static string MenuFun1 {
            get {
                return ResourceManager.GetString("MenuFun1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        internal static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string MenuHome1 {
            get {
                return ResourceManager.GetString("MenuHome1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIBRARIAN RESOURCES.
        /// </summary>
        internal static string MenuLibrary {
            get {
                return ResourceManager.GetString("MenuLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Librarian Resources.
        /// </summary>
        internal static string MenuLibrary1 {
            get {
                return ResourceManager.GetString("MenuLibrary1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representative.
        /// </summary>
        internal static string MenuRep {
            get {
                return ResourceManager.GetString("MenuRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representative.
        /// </summary>
        internal static string MenuRep1 {
            get {
                return ResourceManager.GetString("MenuRep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Penworthy.
        /// </summary>
        internal static string MenuShop {
            get {
                return ResourceManager.GetString("MenuShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Penworthy.
        /// </summary>
        internal static string MenuShop1 {
            get {
                return ResourceManager.GetString("MenuShop1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Merged Quote.
        /// </summary>
        internal static string MergeButtonText {
            get {
                return ResourceManager.GetString("MergeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge.
        /// </summary>
        internal static string MergeText {
            get {
                return ResourceManager.GetString("MergeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        internal static string ModifiedDateText {
            get {
                return ResourceManager.GetString("ModifiedDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $400.00.
        /// </summary>
        internal static string money {
            get {
                return ResourceManager.GetString("money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $20000.
        /// </summary>
        internal static string money1 {
            get {
                return ResourceManager.GetString("money1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  My .
        /// </summary>
        internal static string MyText {
            get {
                return ResourceManager.GetString("MyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.  Your DW selection list always defaults to the &quot;New&quot; Category. View any other category by clicking the check box. The number of titles in each of your decision categories displays behind the category..
        /// </summary>
        internal static string NewCategoryText {
            get {
                return ResourceManager.GetString("NewCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New this month.
        /// </summary>
        internal static string NewthisMonthText {
            get {
                return ResourceManager.GetString("NewthisMonthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nonfiction.
        /// </summary>
        internal static string NonFictionText {
            get {
                return ResourceManager.GetString("NonFictionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books #.
        /// </summary>
        internal static string NoofBooksText {
            get {
                return ResourceManager.GetString("NoofBooksText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string NoofCarts {
            get {
                return ResourceManager.GetString("NoofCarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string NoofCarts1 {
            get {
                return ResourceManager.GetString("NoofCarts1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string NoofItems {
            get {
                return ResourceManager.GetString("NoofItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Items.
        /// </summary>
        internal static string NoofItemsText {
            get {
                return ResourceManager.GetString("NoofItemsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO required, AR hold, ship only to warehouse!!!.
        /// </summary>
        internal static string NotificationText {
            get {
                return ResourceManager.GetString("NotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off-List-Date.
        /// </summary>
        internal static string OffListDateText {
            get {
                return ResourceManager.GetString("OffListDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OffList items that were deleted from the quote:.
        /// </summary>
        internal static string OffListItemsText {
            get {
                return ResourceManager.GetString("OffListItemsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Your Decision Wizard selection list defaults to the &quot;one at a time&quot; view. If you prefer to view all titles on one page, click  view all..
        /// </summary>
        internal static string OneatatimeText {
            get {
                return ResourceManager.GetString("OneatatimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-Hand Quantity.
        /// </summary>
        internal static string OnHandQtyText {
            get {
                return ResourceManager.GetString("OnHandQtyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-List-Date.
        /// </summary>
        internal static string OnListDateText {
            get {
                return ResourceManager.GetString("OnListDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only in paper.
        /// </summary>
        internal static string OnlyinPaperText {
            get {
                return ResourceManager.GetString("OnlyinPaperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to titles canceled and not backordered.
        /// </summary>
        internal static string OrderHistoryPdfCanceledText {
            get {
                return ResourceManager.GetString("OrderHistoryPdfCanceledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string OrderText {
            get {
                return ResourceManager.GetString("OrderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string OtherText {
            get {
                return ResourceManager.GetString("OtherText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outside Options:.
        /// </summary>
        internal static string OutsideOptionsText {
            get {
                return ResourceManager.GetString("OutsideOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package membership.
        /// </summary>
        internal static string PackMemershipText {
            get {
                return ResourceManager.GetString("PackMemershipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        internal static string PagesText {
            get {
                return ResourceManager.GetString("PagesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password you entered is not correct for this user email.  If you do not remember your password, click the “reset password” link below to receive an email to change your password. Or contact Penworthy at 800-262-2665 or .
        /// </summary>
        internal static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penworthy ships immediately with no backorders, so you will have your books in days and always get exactly              what you expected.Here is a PDF of your order if you would like to print or save a copy..
        /// </summary>
        internal static string PDFDescription {
            get {
                return ResourceManager.GetString("PDFDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 800-262-2665.
        /// </summary>
        internal static string PenworthyContactNumber {
            get {
                return ResourceManager.GetString("PenworthyContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penworthy Prebound Book.
        /// </summary>
        internal static string PenworthyPreBoundBookText {
            get {
                return ResourceManager.GetString("PenworthyPreBoundBookText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penworthy.
        /// </summary>
        internal static string PenworthyText {
            get {
                return ResourceManager.GetString("PenworthyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (777)123-4567.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string PhoneText {
            get {
                return ResourceManager.GetString("PhoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture Books 8x8.
        /// </summary>
        internal static string PictureBook8Text {
            get {
                return ResourceManager.GetString("PictureBook8Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture Books.
        /// </summary>
        internal static string PictureBookText {
            get {
                return ResourceManager.GetString("PictureBookText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placement Location Reference.
        /// </summary>
        internal static string PlacementLocationtext {
            get {
                return ResourceManager.GetString("PlacementLocationtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to request a Penworthy Prebound Book sample and conduct your own experiment. Once you see the difference for yourself, it&apos;s clear that Penworthy Prebound Books are the best choice for your collection..
        /// </summary>
        internal static string PreboundEmailRequestText {
            get {
                return ResourceManager.GetString("PreboundEmailRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headstart | Preschool.
        /// </summary>
        internal static string PreSchoolText {
            get {
                return ResourceManager.GetString("PreSchoolText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string PreviewText {
            get {
                return ResourceManager.GetString("PreviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string PriceText {
            get {
                return ResourceManager.GetString("PriceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string ProductsText {
            get {
                return ResourceManager.GetString("ProductsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ProductTypeText {
            get {
                return ResourceManager.GetString("ProductTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotional.
        /// </summary>
        internal static string PromotionalText {
            get {
                return ResourceManager.GetString("PromotionalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protector.
        /// </summary>
        internal static string ProtectorText {
            get {
                return ResourceManager.GetString("ProtectorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        internal static string PublisherText {
            get {
                return ResourceManager.GetString("PublisherText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puppet.
        /// </summary>
        internal static string PuppetsText {
            get {
                return ResourceManager.GetString("PuppetsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchasing history.
        /// </summary>
        internal static string PurchaseHistoryText {
            get {
                return ResourceManager.GetString("PurchaseHistoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUESTION:    Should we create it as an image?.
        /// </summary>
        internal static string QuestionText {
            get {
                return ResourceManager.GetString("QuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string QunatityText {
            get {
                return ResourceManager.GetString("QunatityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string QuoteCreatedDateText {
            get {
                return ResourceManager.GetString("QuoteCreatedDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table&gt;&lt;tr&gt;&lt;td colspan=&quot;{0}&quot;&gt;Sales Tax:&lt;td&gt;{1}&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td colspan=&quot;{0}&quot; &gt;Total Price :&lt;/td&gt;&lt;td&gt;{2}&lt;/td&gt;&lt;/tr&gt; &lt;tr&gt;&lt;td colspan=&quot;11&quot; class=&quot;hide place-left text-left&quot; style=&quot;font-size:8pt;&quot;&gt;This is an order acknowledgement. Your final invoice will be included with your shipment.&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;.
        /// </summary>
        internal static string QuoteEmailExcelFooter {
            get {
                return ResourceManager.GetString("QuoteEmailExcelFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table&gt;&lt;tr&gt;&lt;td colspan=&quot;5&quot;&gt;&lt;/td&gt;&lt;td&gt;Net Invoice:&lt;/td&gt;&lt;td&gt;{0}&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td colspan=&quot;5&quot; style=&quot;text-align:center&quot;&gt; &lt;/td&gt;&lt;td&gt;Shipping &amp; Handling :&lt;/td&gt;&lt;td&gt;{1}&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td colspan=&quot;5&quot; style=&quot;text-align:center&quot;&gt;&lt;/td&gt;&lt;td&gt;Invoice Total: &lt;/td&gt;&lt;td&gt;{2}&lt;/td&gt;&lt;/tr&gt;  &lt;tr&gt;&lt;td colspan=&quot;11&quot; class=&quot;hide place-left text-left&quot; style=&quot;font-size:8pt;&quot;&gt;This is an order acknowledgement. Your final invoice will be included with your shipment.&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;.
        /// </summary>
        internal static string QuoteEmailExcelFooterTable {
            get {
                return ResourceManager.GetString("QuoteEmailExcelFooterTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table&gt;
        ///&lt;tr&gt;    
        /// &lt;td&gt;&lt;/td&gt;
        ///        &lt;td colspan=&quot;&quot;&gt;&lt;/td&gt;
        ///        &lt;td  style=&quot;height: 80px&quot;&gt;  &lt;img src=&quot;{0}/Images/excelpenworthylogo.jpg&quot; /&gt;&lt;/td&gt;
        ///        &lt;td&gt;&lt;/td&gt;
        ///   &lt;td&gt;&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///    &lt;tr&gt;
        ///         &lt;td &gt;&lt;/td&gt;
        ///        &lt;td&gt;Current Date: {1}&lt;/td&gt;
        ///        &lt;td&gt;219 N. Milwaukee St. &lt;/td&gt;
        ///        &lt;td&gt;Quote Number :&lt;/td&gt;
        ///        &lt;td style=&quot;text-align: left&quot;&gt;{2}&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///
        ///    &lt;tr&gt;
        ///  &lt;td &gt;&lt;/td&gt;
        ///        &lt;td&gt;For questions call:&lt;/td&gt;
        ///        &lt;td&gt;Milwaukee, WI 53202&lt;/td&gt;
        ///        &lt;td&gt;Custo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QuoteEmailExcelHeaderTable {
            get {
                return ResourceManager.GetString("QuoteEmailExcelHeaderTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order History :.
        /// </summary>
        internal static string QuoteHistoryText {
            get {
                return ResourceManager.GetString("QuoteHistoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1001.
        /// </summary>
        internal static string QuoteID {
            get {
                return ResourceManager.GetString("QuoteID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote ID.
        /// </summary>
        internal static string QuoteIDText {
            get {
                return ResourceManager.GetString("QuoteIDText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        internal static string QuoteModifiedDateText {
            get {
                return ResourceManager.GetString("QuoteModifiedDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote Type.
        /// </summary>
        internal static string QuoteTypeText {
            get {
                return ResourceManager.GetString("QuoteTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title,ItemId,Author,ISBN,AR,Lexile,ItemPrice,Quantity,Price,Type.
        /// </summary>
        internal static string QuoteuserSelection {
            get {
                return ResourceManager.GetString("QuoteuserSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RC level.
        /// </summary>
        internal static string RCLevelText {
            get {
                return ResourceManager.GetString("RCLevelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RC Quiz #.
        /// </summary>
        internal static string RCQuizText {
            get {
                return ResourceManager.GetString("RCQuizText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readers, not leveled.
        /// </summary>
        internal static string ReadersnotleveledText {
            get {
                return ResourceManager.GetString("ReadersnotleveledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Counts.
        /// </summary>
        internal static string ReadingCountText {
            get {
                return ResourceManager.GetString("ReadingCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading level/program.
        /// </summary>
        internal static string ReadingProgramText {
            get {
                return ResourceManager.GetString("ReadingProgramText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rep Comments :.
        /// </summary>
        internal static string RepCommentsText {
            get {
                return ResourceManager.GetString("RepCommentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representative.
        /// </summary>
        internal static string RepresentativeText {
            get {
                return ResourceManager.GetString("RepresentativeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Source.
        /// </summary>
        internal static string ReviewSourceText {
            get {
                return ResourceManager.GetString("ReviewSourceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        internal static string RowFilterText {
            get {
                return ResourceManager.GetString("RowFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Science.
        /// </summary>
        internal static string ScienceText {
            get {
                return ResourceManager.GetString("ScienceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penworthy&apos;s expertise is helping you keep your collection fresh and relevant with new titles every month, including the series and characters that kids are requesting today. Penworthy&apos;s I Love My Library Collection shown below is a great example of some of our most popular titles today.  If you don&apos;t find what you are looking  for in your search, just give us a call. Your Penworthy representative will put together a suggestion list based on your specific interests and needs..
        /// </summary>
        internal static string SearchDescription {
            get {
                return ResourceManager.GetString("SearchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results : .
        /// </summary>
        internal static string SearchResult {
            get {
                return ResourceManager.GetString("SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See all.
        /// </summary>
        internal static string SeeAllText {
            get {
                return ResourceManager.GetString("SeeAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string SelectText {
            get {
                return ResourceManager.GetString("SelectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series purchased before.
        /// </summary>
        internal static string SeriesPurchasedBeforeText {
            get {
                return ResourceManager.GetString("SeriesPurchasedBeforeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        internal static string SeriesText {
            get {
                return ResourceManager.GetString("SeriesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Description.
        /// </summary>
        internal static string SetDescriptionText {
            get {
                return ResourceManager.GetString("SetDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Name.
        /// </summary>
        internal static string SetNameText {
            get {
                return ResourceManager.GetString("SetNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set #.
        /// </summary>
        internal static string SetNoText {
            get {
                return ResourceManager.GetString("SetNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AR level.
        /// </summary>
        internal static string SetPageARLevel {
            get {
                return ResourceManager.GetString("SetPageARLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        internal static string SetPageCharacter {
            get {
                return ResourceManager.GetString("SetPageCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CopyRight.
        /// </summary>
        internal static string SetPageCopyRight {
            get {
                return ResourceManager.GetString("SetPageCopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dewey.
        /// </summary>
        internal static string SetPageDewey {
            get {
                return ResourceManager.GetString("SetPageDewey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest grade.
        /// </summary>
        internal static string SetPageInterestGrade {
            get {
                return ResourceManager.GetString("SetPageInterestGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        internal static string SetPageISBN {
            get {
                return ResourceManager.GetString("SetPageISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item #.
        /// </summary>
        internal static string SetPageItem {
            get {
                return ResourceManager.GetString("SetPageItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lexile.
        /// </summary>
        internal static string SetPageLexile {
            get {
                return ResourceManager.GetString("SetPageLexile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        internal static string SetPagePages {
            get {
                return ResourceManager.GetString("SetPagePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RC level.
        /// </summary>
        internal static string SetPageRCLevel {
            get {
                return ResourceManager.GetString("SetPageRCLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        internal static string SetPageSeries {
            get {
                return ResourceManager.GetString("SetPageSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string SetPageSize {
            get {
                return ResourceManager.GetString("SetPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelf Ready Unit.
        /// </summary>
        internal static string ShelfReadyUnitText {
            get {
                return ResourceManager.GetString("ShelfReadyUnitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an order acknowledgement. Your final invoice will be included with your shipment..
        /// </summary>
        internal static string ShipmentText {
            get {
                return ResourceManager.GetString("ShipmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Cart.
        /// </summary>
        internal static string ShoppingCartliText {
            get {
                return ResourceManager.GetString("ShoppingCartliText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Cart :.
        /// </summary>
        internal static string ShoppingCartText {
            get {
                return ResourceManager.GetString("ShoppingCartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Cart.
        /// </summary>
        internal static string ShoppingCartText1 {
            get {
                return ResourceManager.GetString("ShoppingCartText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title,ItemId,Series,Author,ISBN,AR,Lexile,ItemPrice,Quantity,Price,Type.
        /// </summary>
        internal static string ShoppingCartuserSelection {
            get {
                return ResourceManager.GetString("ShoppingCartuserSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        internal static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Images.
        /// </summary>
        internal static string ShowImages {
            get {
                return ResourceManager.GetString("ShowImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign in to see your Decision Wizard selection list or add items to your shopping cart.
        /// </summary>
        internal static string SignInRecommendationText {
            get {
                return ResourceManager.GetString("SignInRecommendationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignInText {
            get {
                return ResourceManager.GetString("SignInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string SignOutText {
            get {
                return ResourceManager.GetString("SignOutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string SizeText {
            get {
                return ResourceManager.GetString("SizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small press.
        /// </summary>
        internal static string SmallPressText {
            get {
                return ResourceManager.GetString("SmallPressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Studies.
        /// </summary>
        internal static string SocialText {
            get {
                return ResourceManager.GetString("SocialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Per Book Charge.
        /// </summary>
        internal static string SpecialBookChargeText {
            get {
                return ResourceManager.GetString("SpecialBookChargeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Bulk Charge.
        /// </summary>
        internal static string SpecialBulkChargeText {
            get {
                return ResourceManager.GetString("SpecialBulkChargeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Instructions.
        /// </summary>
        internal static string SpecialInstructionsText {
            get {
                return ResourceManager.GetString("SpecialInstructionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Puppets.
        /// </summary>
        internal static string StagePuppetText {
            get {
                return ResourceManager.GetString("StagePuppetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string SubjectText {
            get {
                return ResourceManager.GetString("SubjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string SubmitText {
            get {
                return ResourceManager.GetString("SubmitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summer reading - Fizz, Boom, Read.
        /// </summary>
        internal static string SummerReadingFizzText {
            get {
                return ResourceManager.GetString("SummerReadingFizzText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summer reading - PAWS.
        /// </summary>
        internal static string SummerReadingPAWSText {
            get {
                return ResourceManager.GetString("SummerReadingPAWSText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are viewing the Tabular View.
        /// </summary>
        internal static string TabularViewText {
            get {
                return ResourceManager.GetString("TabularViewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to titles in collection.
        /// </summary>
        internal static string TitlesCollectionText {
            get {
                return ResourceManager.GetString("TitlesCollectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to titles.
        /// </summary>
        internal static string TitlesText {
            get {
                return ResourceManager.GetString("TitlesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string TitleText {
            get {
                return ResourceManager.GetString("TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Down.
        /// </summary>
        internal static string TopDownText {
            get {
                return ResourceManager.GetString("TopDownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateCollection.
        /// </summary>
        internal static string UpdateCollectionText {
            get {
                return ResourceManager.GetString("UpdateCollectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string UpdateText {
            get {
                return ResourceManager.GetString("UpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunatly the password entered does not match this Email Address. Please reset password or contact Penworthy at 800-262-2665 for assistance.
        /// </summary>
        internal static string UserErrorText {
            get {
                return ResourceManager.GetString("UserErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        internal static string VerticalBottomUpText {
            get {
                return ResourceManager.GetString("VerticalBottomUpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Label Alignment Illustrations:.
        /// </summary>
        internal static string VerticalLabelIllustrationText {
            get {
                return ResourceManager.GetString("VerticalLabelIllustrationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        internal static string verticalTopDownText {
            get {
                return ResourceManager.GetString("verticalTopDownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Penworthy Collection.
        /// </summary>
        internal static string ViewCollectionText {
            get {
                return ResourceManager.GetString("ViewCollectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Quote.
        /// </summary>
        internal static string ViewQuoteText {
            get {
                return ResourceManager.GetString("ViewQuoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string ViewText {
            get {
                return ResourceManager.GetString("ViewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why Penworthy Prebound Books Are Better: a True Story.
        /// </summary>
        internal static string WhyPenworthyText {
            get {
                return ResourceManager.GetString("WhyPenworthyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We gave a Penworthy Prebound Book to a prospective customer and asked her to put it into circulation to personally see our books’ durability. She took it a step further and bought a similar title from another prebound vendor and put both into circulation.  These photos show the results of her experiment. Both books are classified as prebound. Both are two years old. Both circulated 34 times. That’s where the similarities end. The Penworthy Prebound Book looks almost new while the other book shows significan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WhyPreboundDescText {
            get {
                return ResourceManager.GetString("WhyPreboundDescText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Click YES, NO or MAYBE to indicate your choice on each title.
        /// </summary>
        internal static string YesNoMayBeText {
            get {
                return ResourceManager.GetString("YesNoMayBeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Your &quot;Yes&quot; titles are automatically put in your shopping cart and your total shows in the upper right corner of your screen. Click Order Now to review your items and place your order..
        /// </summary>
        internal static string YesTitleText {
            get {
                return ResourceManager.GetString("YesTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Decision Wizard®  list is a quick, easy way to make your book selections.  Click Yes, Maybe or No to indicate your choice. Your YES titles are put into your shopping cart for you to submit as your order. Your NO  titles are deleted when your order is placed.  Any titles you didn&apos;t have time to review and your MAYBE titles are held in your Decision Wizard tool for next time..
        /// </summary>
        internal static string YourDecision_WizardText {
            get {
                return ResourceManager.GetString("YourDecision WizardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z - Other Position; Document in comments.
        /// </summary>
        internal static string zPositionText {
            get {
                return ResourceManager.GetString("zPositionText", resourceCulture);
            }
        }
    }
}
