using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TPC.Common.Enumerations
{
    public enum PackageEnums
    {

        Classification = 1,
        BookFormat = 2,
        ReadingLevel = 3,
        Subject = 4,
        PurchasingHistory = 5,
        ReadingProgram = 6,
        Puppets = 7,
        Fiction = 8,
        Nonfiction = 9,
        ActivityGraphic = 10,
        ChapterBooks = 11,
        PictureBooks = 12,
        PreschoolGrade1 = 13,
        Grades2to3 = 14,
        Grades4Above = 15,
        ArtsRecreationConcepts = 16,
        History = 17,
        LanguageLiterature = 18,
        Science = 19,
        SocialStudies = 20,
        CharacterPurchasedBefore = 21,
        SeriesPurchasedBefore = 22,
        ARLevel = 23,
        LexileLevel = 24,
        RCLevel = 25,
        HandPuppets = 26,
        CharacterPuppets = 27,
        FingerPuppets = 28,
        StagePuppets = 29,
        Dewey = 30

        //Prebound = 2,
        //Library = 3,
        //Board = 4,
        //Picture = 5,
        //PictureBooks8x8 = 6,
        //LeveledReaders = 7,
        //ReadersNotLeveled = 8,
        //Chapter = 9,
        //Activity = 10,
        //Graphics = 11,
        //GradesP1 = 13,
        //Grades23 = 14,
        //Grades4 = 15,
        //AcceleratedReader = 15,
        //Lexile = 16,
        //ReadingCounts = 17,
        //Fiction = 18,
        //Nonfiction = 19,
        //ArtsRecreation = 20,
        //Concepts = 21,
        //History = 22,
        //LanguageLiterature = 23,
        //Science = 24,
        //SocialStudies = 25,
        //FolkmanisPuppets = 26,
        //CharacterPuppets = 27,
        //FingerPuppets = 28,
        //HandPuppets = 29,
        //StagePuppets = 30,
        //CharacterPurchasedBefore = 32,
        //SeriesPurchasedBefore = 33,
        //BooksForBoys = 34,
        //BooksForGirls = 35,
        //HeadstartPreschool = 36,
        //Holiday = 37,
        //NewThisMonth = 38,
        //Onlyinpaper = 39,
        //SmallPress = 40,
        //SummerReadingFizzBoomRead = 41,
        //SummerReadingPAWS = 42,
        //Lego = 43,
        //AR20 = 44,
        //Disney = 45,
        //Superhero = 46,
        //TopSellingCharacters = 47,
        //TopSellingSeries = 48,
        //PrincessesandFairies = 49,
        //StarWars = 50,
        //All = 53,
        //LargeFormatPictureBooks = 54,
        //CommonCoreScience = 55,
        //CommonCoreSocialStudies = 56,
        //CommonCoreLiterature = 57,
        //StatesandCountries = 58,
        //LastChancetitles = 59,
        //Dewey = 60,
        //EntirePenworthyCollection = 61
    }
}
