//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUserType
    {
        public AppUserType()
        {
            this.AppUsers = new HashSet<AppUser>();
        }
    
        public int UserTypeID { get; set; }
        public string UserType { get; set; }
    
        public virtual ICollection<AppUser> AppUsers { get; set; }
    }
}
