//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogSubjectoptionShelfReady
    {
        public CatalogSubjectoptionShelfReady()
        {
            this.CatalogSubjectOptionShelfReadyValues = new HashSet<CatalogSubjectOptionShelfReadyValue>();
        }
    
        public int CSOShelfReadyID { get; set; }
        public int CSOID { get; set; }
        public int ShelfReadyCount { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual CatalogSubjectOption CatalogSubjectOption { get; set; }
        public virtual ICollection<CatalogSubjectOptionShelfReadyValue> CatalogSubjectOptionShelfReadyValues { get; set; }
    }
}
