//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogInformation
    {
        public CatalogInformation()
        {
            this.CatalogSubjects = new HashSet<CatalogSubject>();
        }
    
        public int CatalogInfoID { get; set; }
        public string CatalogInfoName { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<CatalogSubject> CatalogSubjects { get; set; }
    }
}
