//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogSubjectOptionShelfReadyValue
    {
        public CatalogSubjectOptionShelfReadyValue()
        {
            this.CustomerCatalogShelfReadyInformations = new HashSet<CustomerCatalogShelfReadyInformation>();
        }
    
        public int CSOShelfReadyvalueID { get; set; }
        public int CSOValueID { get; set; }
        public int CSOShelfReadyID { get; set; }
        public string CSOShelfReadyValue { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime Updateddate { get; set; }
    
        public virtual CatalogSubjectoptionShelfReady CatalogSubjectoptionShelfReady { get; set; }
        public virtual CatalogSubjectOptionValue CatalogSubjectOptionValue { get; set; }
        public virtual ICollection<CustomerCatalogShelfReadyInformation> CustomerCatalogShelfReadyInformations { get; set; }
    }
}
