//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogSubjectOptionValue
    {
        public CatalogSubjectOptionValue()
        {
            this.CatalogSoftwareVersionMappings = new HashSet<CatalogSoftwareVersionMapping>();
            this.CatalogSoftwareVersionMappings1 = new HashSet<CatalogSoftwareVersionMapping>();
            this.CatalogSubjectOptionProtectorValues = new HashSet<CatalogSubjectOptionProtectorValue>();
            this.CatalogSubjectOptionShelfReadyValues = new HashSet<CatalogSubjectOptionShelfReadyValue>();
            this.CustomerCatalogInformations = new HashSet<CustomerCatalogInformation>();
        }
    
        public int CatalogSubjectOptionValueID { get; set; }
        public Nullable<int> CatalogSubjectOptionID { get; set; }
        public string CatalogSubjectOptionValue1 { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<CatalogSoftwareVersionMapping> CatalogSoftwareVersionMappings { get; set; }
        public virtual ICollection<CatalogSoftwareVersionMapping> CatalogSoftwareVersionMappings1 { get; set; }
        public virtual ICollection<CatalogSubjectOptionProtectorValue> CatalogSubjectOptionProtectorValues { get; set; }
        public virtual CatalogSubjectOption CatalogSubjectOption { get; set; }
        public virtual ICollection<CatalogSubjectOptionShelfReadyValue> CatalogSubjectOptionShelfReadyValues { get; set; }
        public virtual ICollection<CustomerCatalogInformation> CustomerCatalogInformations { get; set; }
    }
}
