//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogSubjectItemIDMapping
    {
        public int CatalogSubjectItemMapID { get; set; }
        public int CatalogSubjectOptionID { get; set; }
        public Nullable<bool> IsCLabelChecked { get; set; }
        public Nullable<bool> ISCSubjProtectorChecked { get; set; }
        public Nullable<bool> IsCSubjSRChecked { get; set; }
        public Nullable<bool> IsCExtraProtectorChecked { get; set; }
        public string ItemID { get; set; }
    
        public virtual CatalogSubjectOption CatalogSubjectOption { get; set; }
        public virtual Item Item { get; set; }
    }
}
