//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogColumnType
    {
        public CatalogColumnType()
        {
            this.CatalogSubjectOptions = new HashSet<CatalogSubjectOption>();
        }
    
        public int CatalogColumnTypeID { get; set; }
        public string CatalogColumnText { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual ICollection<CatalogSubjectOption> CatalogSubjectOptions { get; set; }
    }
}
