//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogSubjectOptionProtectorValue
    {
        public CatalogSubjectOptionProtectorValue()
        {
            this.CustomerCatalogProtectorInformations = new HashSet<CustomerCatalogProtectorInformation>();
        }
    
        public int CSOProtectorvalueID { get; set; }
        public int CSOValueID { get; set; }
        public int CSOProtectorID { get; set; }
        public string CSOProtectorValue { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime Updateddate { get; set; }
    
        public virtual CatalogSubjectOptionProtector CatalogSubjectOptionProtector { get; set; }
        public virtual CatalogSubjectOptionValue CatalogSubjectOptionValue { get; set; }
        public virtual ICollection<CustomerCatalogProtectorInformation> CustomerCatalogProtectorInformations { get; set; }
    }
}
