//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionsDisplayPage
    {
        public CollectionsDisplayPage()
        {
            this.Groups = new HashSet<Group>();
        }
    
        public int PageToDisplayID { get; set; }
        public string PageToDisplayCode { get; set; }
        public string PageToDisplayName { get; set; }
    
        public virtual ICollection<Group> Groups { get; set; }
    }
}
