//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.CustomerCatalogInformations = new HashSet<CustomerCatalogInformation>();
            this.CustomerSeriesCharacters = new HashSet<CustomerSeriesCharacter>();
            this.CustomerTitles = new HashSet<CustomerTitle>();
            this.Users = new HashSet<User>();
        }
    
        public int CustAutoID { get; set; }
        public string CustomerNO { get; set; }
        public string CustomerName { get; set; }
        public bool CustomerStatus { get; set; }
        public Nullable<int> DivisionNo { get; set; }
        public string PID { get; set; }
        public string Email { get; set; }
        public string Comp_PORequirements { get; set; }
        public decimal AgingCategories2 { get; set; }
        public decimal AgingCategories3 { get; set; }
        public decimal AgingCategories4 { get; set; }
        public Nullable<decimal> Comp_stickratecy { get; set; }
        public Nullable<decimal> Comp_stickratepy { get; set; }
        public string TaxScheduleID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual CustomerAddress CustomerAddress { get; set; }
        public virtual ICollection<CustomerCatalogInformation> CustomerCatalogInformations { get; set; }
        public virtual CustomerRep CustomerRep { get; set; }
        public virtual ICollection<CustomerSeriesCharacter> CustomerSeriesCharacters { get; set; }
        public virtual CustomerShipToAddress CustomerShipToAddress { get; set; }
        public virtual ICollection<CustomerTitle> CustomerTitles { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
