//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRepAssignment
    {
        public int CustomerRepAssignmentID { get; set; }
        public string CustomerID { get; set; }
        public Nullable<int> RepID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime Updatedate { get; set; }
    }
}
