//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQ
    {
        public FAQ()
        {
            this.FAQDetails = new HashSet<FAQDetail>();
        }
    
        public int FAQId { get; set; }
        public string FAQQuestion { get; set; }
        public int FAQCategoryID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpadatedDate { get; set; }
    
        public virtual FAQCategory FAQCategory { get; set; }
        public virtual ICollection<FAQDetail> FAQDetails { get; set; }
    }
}
