//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupPackageItem
    {
        public int GroupPackageItemID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> PackageID { get; set; }
        public Nullable<int> PackageSubID { get; set; }
        public string ItemID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Item Item { get; set; }
        public virtual Package Package { get; set; }
        public virtual PackageSubPackage PackageSubPackage { get; set; }
    }
}
