//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.GroupPackages = new HashSet<GroupPackage>();
            this.GroupStyles = new HashSet<GroupStyle>();
            this.GroupPackageItems = new HashSet<GroupPackageItem>();
        }
    
        public int GroupID { get; set; }
        public string GroupName { get; set; }
        public string GroupType { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime Updatedate { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> UserRoleId { get; set; }
        public Nullable<int> PageToDisplay { get; set; }
    
        public virtual CollectionsDisplayPage CollectionsDisplayPage { get; set; }
        public virtual webpages_Roles webpages_Roles { get; set; }
        public virtual ICollection<GroupPackage> GroupPackages { get; set; }
        public virtual ICollection<GroupStyle> GroupStyles { get; set; }
        public virtual ICollection<GroupPackageItem> GroupPackageItems { get; set; }
    }
}
