//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceHistory
    {
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string OrderNo { get; set; }
        public string CustomerPurchaseOrderNo { get; set; }
        public Nullable<int> CustAutoId { get; set; }
        public string TermsCode { get; set; }
        public string ShipVia { get; set; }
        public string ShipTo { get; set; }
        public string FederalId { get; set; }
        public Nullable<int> QuoteID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> ItemsSold { get; set; }
        public Nullable<decimal> ItemsPrice { get; set; }
        public string QuoteType { get; set; }
        public string QuoteTitle { get; set; }
        public string InvoiceType { get; set; }
    }
}
