//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemTag
    {
        public int ItemTagID { get; set; }
        public int ItemID { get; set; }
        public Nullable<int> TagID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public System.DateTime Updatedate { get; set; }
    
        public virtual Tag Tag { get; set; }
    }
}
