//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.CatalogSubjectItemIDMappings = new HashSet<CatalogSubjectItemIDMapping>();
            this.CatalogSubjectOptions = new HashSet<CatalogSubjectOption>();
            this.GroupPackageItems = new HashSet<GroupPackageItem>();
            this.QuoteDetails = new HashSet<QuoteDetail>();
        }
    
        public string ItemID { get; set; }
        public Nullable<int> Type { get; set; }
        public string ProductLine { get; set; }
        public string ProductType { get; set; }
        public string Title { get; set; }
        public Nullable<bool> Previewable { get; set; }
        public string SetProfile { get; set; }
        public string SetName { get; set; }
        public Nullable<int> Copyright { get; set; }
        public Nullable<int> PublisherID { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public string Illustrator { get; set; }
        public string Classification { get; set; }
        public string Format { get; set; }
        public string InterestGrade { get; set; }
        public string Subject { get; set; }
        public string ReviewSource { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ISBN { get; set; }
        public Nullable<System.DateTime> OnListDate { get; set; }
        public int Pages { get; set; }
        public string ARLevel { get; set; }
        public int ARQuiz { get; set; }
        public string LJ { get; set; }
        public string Horn { get; set; }
        public string SLJ { get; set; }
        public string PW { get; set; }
        public string Kirkus { get; set; }
        public Nullable<bool> Booklst { get; set; }
        public string Dewery { get; set; }
        public string RCLevel { get; set; }
        public int RCQuiz { get; set; }
        public string Lexile { get; set; }
        public string Description { get; set; }
        public Nullable<int> Series { get; set; }
        public Nullable<int> PrimeryCharacter { get; set; }
        public string SecondaryCharacter { get; set; }
        public string Size { get; set; }
        public string SellingPoint1 { get; set; }
        public string SellingPoint2 { get; set; }
        public string SellingPoint3 { get; set; }
        public string Package1 { get; set; }
        public string Package2 { get; set; }
        public string Package3 { get; set; }
        public string Package4 { get; set; }
        public string Package5 { get; set; }
        public string Package6 { get; set; }
        public string Package7 { get; set; }
        public string Package8 { get; set; }
        public string Package9 { get; set; }
        public string Package10 { get; set; }
        public string Barcode { get; set; }
        public string OffListDate { get; set; }
        public int OnhandQty { get; set; }
        public Nullable<int> SetID { get; set; }
        public string SetOnly { get; set; }
        public Nullable<int> ItemHistoryID { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<bool> IsInMas { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual ICollection<CatalogSubjectItemIDMapping> CatalogSubjectItemIDMappings { get; set; }
        public virtual ICollection<CatalogSubjectOption> CatalogSubjectOptions { get; set; }
        public virtual ICollection<GroupPackageItem> GroupPackageItems { get; set; }
        public virtual SeriesAndCharacter SeriesAndCharacter { get; set; }
        public virtual ItemHistory ItemHistory { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual SeriesAndCharacter SeriesAndCharacter1 { get; set; }
        public virtual ICollection<QuoteDetail> QuoteDetails { get; set; }
    }
}
