//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailHistory
    {
        public int ID { get; set; }
        public System.DateTime SendDate { get; set; }
        public string FromEmail { get; set; }
        public string To { get; set; }
        public string CC { get; set; }
        public string BCC { get; set; }
        public string MailBody { get; set; }
        public string type { get; set; }
        public Nullable<int> quoteId { get; set; }
        public Nullable<int> PersonId { get; set; }
        public string QuoteTitle { get; set; }
    }
}
