//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public Nullable<int> OrderedQty { get; set; }
        public Nullable<int> ReceivedQty { get; set; }
        public Nullable<int> OnHandQty { get; set; }
        public Nullable<int> CommittedQty { get; set; }
        public Nullable<int> SoldQty { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
