//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public Package()
        {
            this.GroupPackages = new HashSet<GroupPackage>();
            this.GroupPackageItems = new HashSet<GroupPackageItem>();
            this.PackageSubPackages = new HashSet<PackageSubPackage>();
            this.PackageSubPackages1 = new HashSet<PackageSubPackage>();
        }
    
        public int PackageID { get; set; }
        public string PackageName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int Priority { get; set; }
        public Nullable<int> UserRoleId { get; set; }
    
        public virtual ICollection<GroupPackage> GroupPackages { get; set; }
        public virtual ICollection<GroupPackageItem> GroupPackageItems { get; set; }
        public virtual webpages_Roles webpages_Roles { get; set; }
        public virtual ICollection<PackageSubPackage> PackageSubPackages { get; set; }
        public virtual ICollection<PackageSubPackage> PackageSubPackages1 { get; set; }
    }
}
