//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageSubPackage
    {
        public PackageSubPackage()
        {
            this.GroupPackageItems = new HashSet<GroupPackageItem>();
        }
    
        public int PackageSubID { get; set; }
        public int PackageID { get; set; }
        public int SubPackageID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual ICollection<GroupPackageItem> GroupPackageItems { get; set; }
        public virtual Package Package { get; set; }
        public virtual Package Package1 { get; set; }
    }
}
