//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publisher
    {
        public Publisher()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int PublisherID { get; set; }
        public string PublisherName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
        public virtual Publisher Publisher1 { get; set; }
        public virtual Publisher Publisher2 { get; set; }
    }
}
