//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteType
    {
        public QuoteType()
        {
            this.Quotes = new HashSet<Quote>();
            this.QuoteSubmitSaveInfoes = new HashSet<QuoteSubmitSaveInfo>();
        }
    
        public int QuoteTypeID { get; set; }
        public string QuoteTypeText { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual ICollection<Quote> Quotes { get; set; }
        public virtual ICollection<QuoteSubmitSaveInfo> QuoteSubmitSaveInfoes { get; set; }
    }
}
