//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteDetail
    {
        public int QuoteDetailID { get; set; }
        public Nullable<int> QuoteID { get; set; }
        public string ItemID { get; set; }
        public int DWSelectionID { get; set; }
        public int Quantity { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual DWSelectionStatu DWSelectionStatu { get; set; }
        public virtual Item Item { get; set; }
        public virtual Quote Quote { get; set; }
    }
}
