//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteCallTag
    {
        public int QuoteCalTagInfoID { get; set; }
        public Nullable<int> QuoteID { get; set; }
        public Nullable<int> CalTagInfoID { get; set; }
        public string CalTagInfoValue { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual CalTagInfo CalTagInfo { get; set; }
        public virtual Quote Quote { get; set; }
    }
}
