//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public Quote()
        {
            this.QuoteCallTags = new HashSet<QuoteCallTag>();
            this.QuoteDetails = new HashSet<QuoteDetail>();
        }
    
        public int QuoteID { get; set; }
        public string QuoteTitle { get; set; }
        public int UserID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string POText { get; set; }
        public string Comments { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<int> QuoteTypeID { get; set; }
        public Nullable<bool> IncludeCatalogStatus { get; set; }
        public Nullable<System.DateTime> PenworthyUpdatedDate { get; set; }
        public Nullable<System.DateTime> CustomerUpdatedDate { get; set; }
        public Nullable<decimal> QuoteTotalPrice { get; set; }
    
        public virtual QuoteType QuoteType { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<QuoteCallTag> QuoteCallTags { get; set; }
        public virtual ICollection<QuoteDetail> QuoteDetails { get; set; }
        public virtual QuoteSubmitSaveInfo QuoteSubmitSaveInfo { get; set; }
    }
}
