//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteSubmitSaveInfo
    {
        public int QuoteID { get; set; }
        public Nullable<int> SourceTypeID { get; set; }
        public Nullable<int> QuoteTypeID { get; set; }
        public Nullable<int> InvoiceRecipientID { get; set; }
        public string PoNo { get; set; }
        public Nullable<System.DateTime> FutureBillDate { get; set; }
        public string QuoteSubmitComments { get; set; }
        public string QuoteBillReference { get; set; }
        public string PayerID { get; set; }
        public string ShipItemsToID { get; set; }
        public string AdditionalInvoiceRecipientId { get; set; }
        public Nullable<decimal> DBPrice { get; set; }
        public bool IsRepoHold { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Quote Quote { get; set; }
        public virtual QuoteType QuoteType { get; set; }
        public virtual SourceType SourceType { get; set; }
    }
}
