//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepUser
    {
        public RepUser()
        {
            this.CustomerReps = new HashSet<CustomerRep>();
        }
    
        public int RepUserID { get; set; }
        public int UserID { get; set; }
        public int RepID { get; set; }
        public Nullable<int> ARDivision { get; set; }
        public string Title { get; set; }
        public string SalesCoordinator { get; set; }
        public string AddressLine1 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> ZipCode { get; set; }
        public bool IsActive { get; set; }
        public string PhoneCustomerService { get; set; }
        public string PhoneDirect { get; set; }
        public string Biodata { get; set; }
        public string AuditFlag { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual ICollection<CustomerRep> CustomerReps { get; set; }
        public virtual User User { get; set; }
    }
}
