//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeriesAndCharacter
    {
        public SeriesAndCharacter()
        {
            this.CustomerSeriesCharacters = new HashSet<CustomerSeriesCharacter>();
            this.Items = new HashSet<Item>();
            this.Items1 = new HashSet<Item>();
        }
    
        public int SCID { get; set; }
        public string SCText { get; set; }
        public string SCType { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual ICollection<CustomerSeriesCharacter> CustomerSeriesCharacters { get; set; }
        public virtual ICollection<Item> Items { get; set; }
        public virtual ICollection<Item> Items1 { get; set; }
    }
}
