//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Quotes = new HashSet<Quote>();
        }
    
        public int StatusID { get; set; }
        public string StatusFlag { get; set; }
        public string StatusDescription { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual ICollection<Quote> Quotes { get; set; }
    }
}
