//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.CustomerTags = new HashSet<CustomerTag>();
            this.ItemTags = new HashSet<ItemTag>();
        }
    
        public int TagID { get; set; }
        public int TagTypeID { get; set; }
        public string TagName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual ICollection<CustomerTag> CustomerTags { get; set; }
        public virtual ICollection<ItemTag> ItemTags { get; set; }
        public virtual TagType TagType { get; set; }
    }
}
