//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagType
    {
        public TagType()
        {
            this.Tags = new HashSet<Tag>();
        }
    
        public int TagTypeID { get; set; }
        public string TagTypeName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
