//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.CustomerCatalogInformations = new HashSet<CustomerCatalogInformation>();
            this.Quotes = new HashSet<Quote>();
            this.RepUsers = new HashSet<RepUser>();
            this.UserPreferences = new HashSet<UserPreference>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string CommunicationEmail { get; set; }
        public Nullable<int> CustAutoID { get; set; }
        public Nullable<bool> IsPrimaryUser { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<bool> ISActive { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<CustomerCatalogInformation> CustomerCatalogInformations { get; set; }
        public virtual ICollection<Quote> Quotes { get; set; }
        public virtual ICollection<RepUser> RepUsers { get; set; }
        public virtual ICollection<UserPreference> UserPreferences { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
}
