//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDWMailHistory
    {
        public int MailHistoryID { get; set; }
        public System.DateTime SendDate { get; set; }
        public string To { get; set; }
        public string type { get; set; }
        public Nullable<int> quoteId { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<int> QuoteTypeID { get; set; }
        public string QuoteTitle { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string CustomerNO { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> CustAutoID { get; set; }
        public string FromEmail { get; set; }
        public Nullable<decimal> QuoteTotalPrice { get; set; }
    }
}
