//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vQuote
    {
        public Nullable<int> QuoteID { get; set; }
        public string QuoteTitle { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> QuoteTypeID { get; set; }
        public Nullable<bool> IncludeCatalogStatus { get; set; }
        public Nullable<System.DateTime> PenworthyUpdatedDate { get; set; }
        public Nullable<System.DateTime> CustomerUpdatedDate { get; set; }
        public string UserName { get; set; }
        public Nullable<int> CustAutoID { get; set; }
        public string CustomerNO { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> DivisionNo { get; set; }
        public string PID { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string QuoteTypeText { get; set; }
        public string StatusDescription { get; set; }
        public Nullable<int> RepUserID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<decimal> QuoteTotalPrice { get; set; }
    }
}
