//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPC.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vWebUser
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string CommunicationEmail { get; set; }
        public Nullable<int> CustAutoID { get; set; }
        public Nullable<bool> IsPrimaryUser { get; set; }
        public Nullable<int> PersonID { get; set; }
        public string CustomerNO { get; set; }
        public string CustomerName { get; set; }
        public string PID { get; set; }
    }
}
